feat: add new color
fmaclen/chromabox pull request #14
Opened 2024-11-22 03:53 UTC by GregoMac1

Closes #2 #3

2024-11-22 03:56 UTC, GregoMac1 commented on static/styles.css
> +.color-picker .wrapper {
These are the class names of the color picker. I had to do this because the component does not provide any option to override these settings.

2024-11-22 03:57 UTC, GregoMac1 commented on src/routes/colors/ColorPaletteCard.svelte
> +			<input type="text" value={'color.toOklchString()'} oninput={handleColorInput} />
We have a problem: `colord` does not support OKLCH. I think we'll have to choose another library (for example [this one](https://www.npmjs.com/package/colorjs.io)).

2024-11-22 04:00 UTC, GregoMac1 commented on src/routes/colors/ColorPaletteCard.svelte
> +	<ColorPicker bind:hex components={ChromeVariant} isDialog={false} sliderDirection="horizontal" />
The standard approach would have been to directly bind `color` instead of `hex` but for some reason, when I updated the color in any of the inputs, the color picker didn't update.

I also tried to store `color` as a `$state` variable instead of a prop, but it was the same.

The only way I found to make the color picker to update from the input was binding it to `hex`.

2024-11-22 04:01 UTC, GregoMac1 commented on src/routes/colors/ColorPaletteCard.svelte
> +	let hex = $state(color.toHex());
This was added because of the issue described in the next comment.

2024-11-22 04:03 UTC, GregoMac1 commented
@fmaclen I added some comments to let you know the problems of the current implementation. Please let me know what you think.

2024-11-23 23:59 UTC, fmaclen requested changes

2024-11-23 23:59 UTC, fmaclen commented on src/routes/+page.svelte
> +</script>
Why not render the UI directly in the root `/`?

2024-11-23 23:59 UTC, fmaclen commented on src/routes/colors/+page.svelte
> +<p>A creative tool to experiment with and perfect your color combinations.</p>
I think you are using an old version of the design, we removed this text.

Here's the most recent (still WIP) version:

![image](https://github.com/user-attachments/assets/94b8ba12-9a28-438d-a2c0-f617bb3bd5d8)

2024-11-23 23:59 UTC, fmaclen commented on src/routes/colors/ColorPaletteCard.svelte
> +			<input type="text" value={'color.toOklchString()'} oninput={handleColorInput} />
Let's remove OKLCH for now, I need to do more research about that color format.

2024-11-23 23:59 UTC, fmaclen commented on src/routes/colors/ColorPaletteCard.svelte
> +	<ColorPicker bind:hex components={ChromeVariant} isDialog={false} sliderDirection="horizontal" />
I'm not sure, but I think it's not binding because you need to use [`$bindable`](https://svelte.dev/docs/svelte/$bindable) here:

```
let { color }: { color: Colord } = $props();
```

2024-11-23 23:59 UTC, fmaclen commented on static/styles.css
> +.color-picker .wrapper {
Gotcha, the _Svelte-way_ of doing this is to keep the styles in the component, but using [`:global()`](https://svelte.dev/docs/svelte/global-styles).

So it'd look like:

```html
<style>
.color-picker-container {
  :global(.color-picker .wrapper) {
     // ...
  }
}
</style>
```

I'm worried about the `!important`'s, there has to be a way to customize the styles without using them, it's a code smell. See if using `:global()` adds enough specificity so we can remove the `!important`'s.

2024-11-23 23:59 UTC, fmaclen commented on src/routes/colors/ColorPaletteCard.svelte
> +			<input type="text" value={color.toHex()} oninput={handleColorInput} />
Can we try calling `handleColorInput` on `onblur`?
I tried typing colors manually and it kept breaking the color I was typing.

2024-11-25 23:36 UTC, GregoMac1 commented on static/styles.css
> +.color-picker .wrapper {
It worked, thanks!

2024-11-25 23:54 UTC, GregoMac1 commented on src/routes/colors/ColorPaletteCard.svelte
> +	<ColorPicker bind:hex components={ChromeVariant} isDialog={false} sliderDirection="horizontal" />
Okay, I've tried it and got the same result.

Additionally, I tried creating a `$state` just like the `hex` state now but containing the same value as the `color` prop, to see if the problem was about the prop, and I also got the same result. This is the code I used:

```svelte
<script lang="ts">
	...
	let { color }: { color: Colord } = $props();

	let newColor = $state(color);

	$effect(() => {
		newColor = color;
	});

	$effect(() => {
		color = colord(newColor);
	});
	...
</script>

<div class="color-picker-container">
	<ColorPicker
		bind:color={newColor}
		components={ChromeVariant}
		isDialog={false}
		sliderDirection="horizontal"
	/>
	...
</div>
```

My guess is that the `ColorPicker` is implemented in a way which makes the binding work with `hex` but not with `color`.

2024-11-26 00:01 UTC, GregoMac1 commented on src/routes/colors/+page.svelte
> +<p>A creative tool to experiment with and perfect your color combinations.</p>
Nice, thanks!

About the opacity slider/input: currently, it is being handled by the `Colord` object, which adds the opacity to each input when the value is less than 1. Then, the `rgb` text of the rgb input is automatically transformed to `rgba` and `hsl` to `hsla`.

What do you think of this approach? I like it because it makes it easier to copy the value from the input to paste it with the opacity included.

2024-11-26 16:20 UTC, fmaclen commented on src/routes/colors/+page.svelte
> +<p>A creative tool to experiment with and perfect your color combinations.</p>
Yeah, I think your current approach works 👍

2024-11-27 18:22 UTC, fmaclen requested changes
I think we are almost there, left you some cleanup/organizational notes.

2024-11-27 18:22 UTC, fmaclen commented on e2e/colors.test.ts
> +		expect(colorCards.length).toBe(0);
Let's also update the same pattern in the other tests.

2024-11-27 18:22 UTC, fmaclen commented on src/routes/ColorPaletteCard.svelte
> +<script lang="ts">
Let's rename `<ColorPaletteCard>` to `<ColorCard>`, no need to introduce the _concept_ of Palettes yet.

2024-11-27 18:22 UTC, fmaclen commented on e2e/colors.test.ts
> +		const hslInput = page.getByTestId('hsl-input');
I don't understand how this is working 🤷‍♂️ 
I see no `<input>` tags with `data-test-id`.

2024-11-27 18:22 UTC, fmaclen commented on e2e/colors.test.ts
> +test.describe('Color Picker', () => {
Let's try renaming this to `Color card` so it matches the name of the Svelte file.

2024-11-27 18:22 UTC, fmaclen commented on playwright.config.ts
> +	timeout: 5000
Do we need to set a timeout? Otherwise let's keep the default timeout (which I think it's `5000ms`).

2024-11-27 18:22 UTC, fmaclen commented on src/routes/ColorPaletteCard.svelte
> +	.color-picker-container {
Couple of things:
- Let's rename the base class as `.color-card` so it matches the file (and the test)
- These classes are not following the [BEM syntax](https://getbem.com/naming/), here's an example:
```svelte
.color-card { // BLOCK
  &:global(.wrapper) {
    margin: 0;
    border: none;
  }

  &__input-group { // ELEMENT
    display: flex;
    flex-direction: column;
    gap: 5px;

    &--horizontal { // MODIFIER
      flex-direction: row;
    }
  }

  &__input-item {
    display: flex;
    gap: 10px;

    & input {
      width: 100%;
    }
  }

  width: fit-content;
  padding: 10px;
  border: 1px solid rgba(0, 0, 0, 0.25);
  border-radius: 10px;

  &:global(.text-input) {
    display: none;
  }
}
```

Which would generate styles for these selectors:
```
.color-card
.color-card__input-group
.color-card__input-group--horizontal
.color-card__input-item
.color-card__input-item input
```

2024-11-27 18:22 UTC, fmaclen commented on src/routes/ColorPaletteCard.svelte
> +		}
Is `.text-input` something introduced by the color picker library?

2024-11-27 18:29 UTC, fmaclen commented on src/routes/colors/ColorPaletteCard.svelte
> +	<ColorPicker bind:hex components={ChromeVariant} isDialog={false} sliderDirection="horizontal" />
Ok, understood. Can you add anote about this in the code? I'm okay with shipping this if it works, but if I ever need to refactor this code in the future I want to know it deviates from _the standard_.

2024-11-28 23:05 UTC, GregoMac1 commented on e2e/colors.test.ts
> +		const hslInput = page.getByTestId('hsl-input');
😅 It's working because the property is `data-testid` instead of `data-test-id`. [Here](https://github.com/fmaclen/chromabox/blob/7e435ed0acd0a5bb68a50622c0b081e2ce38ec7f/src/routes/ColorPaletteCard.svelte#L38) it is!

2024-11-28 23:07 UTC, GregoMac1 commented on playwright.config.ts
> +	timeout: 5000
I think that the default timeout is 30 seconds. I added the 5 seconds timeout just to save time when a test is not going to pass (for example with a wrong locator, which would take 30 seconds to fail).

2024-11-28 23:08 UTC, GregoMac1 commented on src/routes/ColorPaletteCard.svelte
> +		}
Yes! Correct

2024-11-28 23:28 UTC, GregoMac1 commented on src/routes/ColorPaletteCard.svelte
> +	.color-picker-container {
Got it! Then, I should install `postcss` and `postcss-nested` and configure them, right?

2024-11-29 14:21 UTC, fmaclen commented on playwright.config.ts
> +	timeout: 5000
Ah gotcha, I see now we specified that in Hollama as well 👍

2024-11-29 14:27 UTC, fmaclen commented on e2e/colors.test.ts
> +		const hslInput = page.getByTestId('hsl-input');
Haha I completely missed that detail 😅 

But now that I look at it more closely we shouldn't be using test id's here (or in most places), it's sort of a code smell.

We should use _semantically correct_ fields, for example:

```svelte
		<div class="field">
			<label for="color-hsl">HSL</label>
			<input
				type="text"
				value={color.toHslString()}
				onblur={handleColorInput}
				name="color-hsl"
			/>
		</div>
```

This way you can use `page.getByLabel('HSL')` which makes the test syntax be closer to how a user experiences the layout.

Additionally, `.color-picker-container` should be more like `form.color` (even if we aren't really using the "form" to submit the fields).

And `.color-picker-input-group` should be more like `fieldset.color__fieldset`.

2024-11-30 18:25 UTC, fmaclen approved these changes
Looks good 🚀

2024-11-30 18:25 UTC, fmaclen commented on src/routes/+page.svelte
> +	.color-grid {
No need to make this change now, but `.color-grid` would probably end up being `.palette`.

2024-11-30 23:02 UTC, GregoMac1 commented on src/routes/+page.svelte
> +	.color-grid {
Done!

2024-11-30 23:03 UTC, merged