feat: add variants from color
fmaclen/chromabox pull request #15
Opened 2024-12-05 00:16 UTC by GregoMac1

Closes #4

2024-12-05 14:17 UTC, fmaclen requested changes
This is a great start! 👍 
Let's make sure the variants are generated with decimal points so we avoid duplicates.

2024-12-05 14:17 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +	});
I'm not sure it makes sense to have a function (`generateVariants()`) with arguments that are already accesible by the function.

I imagine you did this so that it triggers the `$effect`, but I think here we could just use [`$derived.by`](https://svelte.dev/docs/svelte/$derived#$derived.by), which would look like this:

```ts
const variants = $derived.by(() => {
  // Logic in generateVariants() goes here 
}
```

This way `variants` will get updated whenever any of the internal variables change.

2024-12-05 14:17 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +	let easingFn = $state('cubicInOut');
Minor thing for code organization, let's keep all of the `let variable = $state()` lines together.

Also, I try to keep all of the Svelte-specific syntax together at the top of each component, so all `$state`, `$effect` & `$derived`'s should be together.

2024-12-05 14:17 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +	let easingFn = $state('cubicInOut');
The default `easingFn` should be `linear`.

2024-12-05 14:17 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +			<div class="variant__box" style:background-color={variant.toHex()}>
![image](https://github.com/user-attachments/assets/396bcdca-8c79-461b-9233-4630a86fb3d1)

Why is it getting rendered as RGB if it's `toHex()`? 🤷‍♂️

2024-12-06 00:09 UTC, GregoMac1 commented
@fmaclen about the decimals, there is a problem.

As you can see in the image below, the lightness for each variant (the logs in the console, on the right) is calculated correctly with decimals.

However, when we create the `const variant = colord({ h: hsl.h, s: hsl.s, l: lightness });`, the lightness is rounded to an integer. In the image, you can see that all the variants with lightness minor than 5.5 are set to 5, and equal or greater than 5.5 are set to 6.

I've looked in the documentation of `Colord`, but I didn't find anything about this situation.

<img width="659" alt="image" src="https://github.com/user-attachments/assets/23d0c947-9f6f-45d1-839a-8a9feb2359bf">

2024-12-06 00:18 UTC, GregoMac1 commented
I've read several articles in StackOverflow and other forums and documentation.

Most answers say that it's not possible to use a float value for lightness, although some say it is. I've also found this [PR](https://github.com/mrdoob/three.js/pull/24461) in which they seem to do it.

2024-12-06 00:40 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +			<option value="12">12</option>
Could we DRY this with a loop?

2024-12-06 00:44 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +				<p class="variant__text">{variant.toHex()} - {variant.toHslString()}</p>
Let's only use `hex()` for now because it's shorter, eventually user will be able to choose which format they want to visualize here.

2024-12-06 01:58 UTC, fmaclen requested changes
Ok, this looks good. Let's finish the tests next.

2024-12-06 01:58 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +		</select>
Wait, sorry, I didn't catch this earlier. It shouldn't be a `<select>`, it should be an `<input type="number" bind:value={steps}>`.

2024-12-06 19:06 UTC, GregoMac1 commented on src/routes/ColorCard.svelte
> +		</select>
Sure! Should it have min and max values? If so, we should also check that the user isn't able to mannually input a lower or higher number than our defined range.

2024-12-06 19:12 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +		</select>
Nah, that's okay for now. Our defined range is made up anyways 😅

2024-12-09 16:52 UTC, GregoMac1 commented
@fmaclen I added some tests.

I have some concerns about the test `should update variants when changing easing function`. I feel it doesn't fully cover the feature, but I don't know how to improve it. Could you give me a hand?

(also, the `lint` is failing but I don't undestand why. It says `package.json` has linting errors, but when I run `npm run lint` locally it doesn't throw anything)

2024-12-09 17:01 UTC, fmaclen commented
> (also, the lint is failing but I don't undestand why. It says package.json has linting errors, but when I run npm run lint locally it doesn't throw anything)

Not sure what was going on there, but I ran `npm run format` and fixed it the warning.

2024-12-09 17:28 UTC, fmaclen requested changes
After playing with the implementation a bit more it looks like `cubic` is not the optimal easing function, we should probably switch to `quad`.

Also left you some notes about the tests.

2024-12-09 17:28 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +	import { cubicIn, cubicInOut, cubicOut, linear } from 'svelte/easing';
Taking a 2nd look at the variants, `cubic` is generating duplicate variants when choosing `cubicIn` and `cubicOut`.

Let's instead use the `quad` function:

![image](https://github.com/user-attachments/assets/8272bc74-678a-43b5-8176-639896f5b61f)

2024-12-09 17:28 UTC, fmaclen commented on e2e/colors.test.ts
> +	});
Need to assert the default number of variants first.
Also need to add negative assertions before changing the number of variants.

2024-12-09 17:28 UTC, fmaclen commented on e2e/colors.test.ts
> +		await hexInput.blur();
You can remove this color change, whatever color is generated at random should also be 100% white/black at the extremes.

2024-12-09 17:28 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +		<select bind:value={easingFn} title="Easing function">
Let's rename this to `Easing`.

2024-12-09 17:28 UTC, fmaclen commented on e2e/colors.test.ts
> +		await page.getByTitle('Steps').fill('9');
I don't think it matters if the middle color is the one chosen, what I think we should test is that specific variants have the colors we expect.

I'd leave the default steps of `12`, assert the 2nd and 11th variants, then change the easing function, assert that the 2nd/11th variants have changed. Rinse and repeat.

Let's add negative assertions after every easing change as well.

2024-12-09 18:08 UTC, fmaclen commented on e2e/colors.test.ts
> +		await expect(variants).toHaveCount(8);
Minor syntax styling, make sure the actions and assertions are all together, only add empty lines after a sequence of assertions, for example:

```
click
click
expect
expect
expect

click
expect

click
expect
expect
```

2024-12-09 18:10 UTC, GregoMac1 commented on e2e/colors.test.ts
> +		await expect(variants).toHaveCount(8);
Sure!

2024-12-09 18:17 UTC, GregoMac1 commented on e2e/colors.test.ts
> +		await page.getByTitle('Steps').fill('9');
Thanks for the help! What do you think now?

2024-12-09 18:31 UTC, fmaclen commented on e2e/colors.test.ts
> +		await page.getByTitle('Steps').fill('9');
What you have now technically works, but if we later update the function to generate variants from `lightness` to `saturation` (or `hue`) the test will still pass and it shouldn't.

We want to make sure we are asserting the right colors, in other words, we need to check that `background-color: #xxxxxx` is correctly calculated for every 2nd/11th variant, for example:

```typescript
// Quad In Out - #ff0000 - 12 steps
await expect(variants.nth(1)).toHaveAttribute('style', /background-color: #fff7f7/);
await expect(variants.nth(10)).toHaveAttribute('style', /background-color: #080000/);
```
We also need to do these types of assertions for the `Linear` variants.

In fact, we should probably update the test name to reflect that we are testing variants for `lightness`.

2024-12-09 19:23 UTC, GregoMac1 commented on e2e/colors.test.ts
> +		await page.getByTitle('Steps').fill('9');
Yeah, I agree. I updated the test with known values for the colors in each case.

2024-12-09 19:27 UTC, fmaclen approved these changes
Awesome, this is looking great! 🚀

2024-12-09 19:34 UTC, merged