feat: add copy buttons to color inputs and variants
fmaclen/chromabox pull request #30
Opened 2024-12-11 23:30 UTC by GregoMac1

I know the final design will have the Copy icon instead of text but I wrote the tests like this for now.

2024-12-12 03:26 UTC, fmaclen requested changes
This is a great start!

Even though the copy buttons will have an icon, they likely have a `title` attribute which I think will work fine with `getByRole('button', { name: 'Copy' })`.

I also think these 2 tests could be also combined into one since they are so small.

Let's continue with the implementation after those minor changes 👍

2024-12-12 03:26 UTC, fmaclen commented on e2e/colors.test.ts
> +		await page.getByRole('button', { name: 'Copy HSL' }).click();
I think it'll be easier to re-use the code if we use `Copy` as the name for every copy button, so I'd remove the color format from the `name` in these.

Instead just use a locator such as `page.locator('.color__input-item', { hasText: 'HSL' }).getByRole('button' ... )`

2024-12-12 14:47 UTC, GregoMac1 commented
@fmaclen I left the 'Copy' text for now until we add the icon.

2024-12-12 16:59 UTC, fmaclen requested changes
Alright, almost there. Just left you a note about DRY'n the Copy button.

2024-12-12 16:59 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +				</button>
I think we have an opportunity to DRY these buttons in a similar way we did in Hollama with [`ButtonCopy`](https://github.com/fmaclen/hollama/blob/main/src/lib/components/ButtonCopy.svelte).

2024-12-12 23:10 UTC, GregoMac1 commented on src/routes/ColorCard.svelte
> +				</button>
Okay! So now is the moment to stop writing pure html code and start defining custom components?

2024-12-12 23:12 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +				</button>
Yeah, sorry. What I meant by writing plain HTML was more because of styling, if there are opportunities to DRY stuff into Svelte components we should do it.

2024-12-12 23:23 UTC, GregoMac1 commented on src/routes/ColorCard.svelte
> +				</button>
You're right. We even have ColorCard defined as a component already 🤦🏻‍♂️

2024-12-12 23:24 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +				</button>
Suele pasar 😅

2024-12-13 16:07 UTC, fmaclen approved these changes
I think this is good to go, but there is one more Copy button we should replace with the new component.

After that, feel free to merge the PR.

2024-12-13 16:07 UTC, fmaclen commented on src/routes/ColorCard.svelte
> +				</button>
This one should be a `<ButtonCopy>` as well.

2024-12-13 17:41 UTC, merged