chore: use own color interfaces
fmaclen/chromabox pull request #38
Opened 2024-12-20 20:17 UTC by GregoMac1

2024-12-20 20:52 UTC, fmaclen requested changes
It might make sense to create a class to handle most of this new behavior.

2024-12-20 20:52 UTC, fmaclen commented on src/lib/colors.ts
> +}
I think all of these interfaces and functions are so closely related that is probably a sign that we should abstract them under a `class Color`.

In Svelte 5 you can create [classes with reactivity](https://svelte.dev/docs/svelte/$state#Classes).

Here's an example from Canutin:
https://github.com/fmaclen/canutin-desktop/blob/v2/src/lib/accounts.svelte.ts

2024-12-20 20:52 UTC, fmaclen commented on src/routes/ColorCard.svelte
>  	<ColorPicker bind:hex components={ChromeVariant} isDialog={false} sliderDirection="horizontal" />
Have you tried binding to `color.hex` now that we got rid of the `colord` library?

2024-12-20 21:45 UTC, GregoMac1 commented on src/routes/ColorCard.svelte
>  	<ColorPicker bind:hex components={ChromeVariant} isDialog={false} sliderDirection="horizontal" />
I had tried but I was having an infinite loop problem. Now I analyzed it again and I came up to the current solution

2024-12-20 22:12 UTC, GregoMac1 commented on src/lib/colors.ts
> +}
I've been thinking about this.

Do you mean we should store the reactive colors (like `colors: $state(...)`) in an instance of the class like for example `colorsManager = new Colors()`?

Or should we use this class as a static class to only provide these helper methods (and keep `colors` stored in `+page.svelte`)?

2024-12-20 22:52 UTC, fmaclen commented on src/lib/colors.ts
> +}
The idea is that you instantiate a [`Context`](https://svelte.dev/docs/svelte/context) that's reactive, works similarly to the stores in Svelte 4.

Here's an example of how it's instantiated in Canutin (though in this case we are only reading the values):
https://github.com/fmaclen/canutin-desktop/blob/v2/src/routes/(app)/accounts/%2Bpage.svelte#L9

Here's a video that explains what I tried to do in Canutin:
https://www.youtube.com/watch?v=e1vlC31Sh34

Not sure, but it might make more sense to create a `class Palette` that includes all of the color math and pass that around, instead of an array of `class Color`.

2024-12-20 23:04 UTC, fmaclen commented on src/routes/ColorCard.svelte
>  	<ColorPicker bind:hex components={ChromeVariant} isDialog={false} sliderDirection="horizontal" />
Ok, I think the new method looks good. It's a bit hard to wrap your head around the syntax at first glance, but it's easier to reason than the 2 `$effect()`'s we had before.

2024-12-21 12:45 UTC, GregoMac1 commented on src/lib/colors.ts
> +}
Thanks for the references!

2024-12-21 12:50 UTC, GregoMac1 commented on src/routes/+layout.svelte
> +	setColorsState();
@fmaclen I tried wrapping the `setColorsState()` in:
- `$effect.pre`
- `$effect`
- `onMount`

But all the options were throwing an error of initialization, so I left it like this as shown in the repo of the video you showed me, see [here](https://github.com/huntabyte/svelte-5-context-classes/blob/d1bced7b3c420d27f47cef313357754ee27fd61c/src/routes/%2Blayout.svelte#L10).

2024-12-21 12:51 UTC, GregoMac1 commented on src/routes/+layout.svelte
> +			{@render children()}
The `slot`s were throwing a deprecation warning so I replaced them for `@render`s.

2024-12-22 17:33 UTC, merged