feat: export variants
fmaclen/chromabox pull request #39
Opened 2024-12-22 21:44 UTC by GregoMac1

2024-12-23 17:36 UTC, fmaclen requested changes
I think this looks good so far 👍 

In general, I'm not sure it's a good idea to rely on `beforeEach`'s. While it's good to DRY stuff in the code, in my experience DRY'ing tests makes them a lot harder to maintain. 

I'm not saying we should never use `beforeEach` but it's okay if we have a little repetition in tests. In this case we can probably do away with the setup block.

It's okay if we keep 3 steps for one of the tests, but let's add some variability to others, maybe 4, 5 or even the default 12 steps. If we do 12 steps, we don't need to check every variant, one or 2 in the middle is probably good enough. 

Could also try different colors and easing functions for every test instead of all the same variants of _linear_ red. 

We also missing tests/assertions for:
- multiple colors
- a color with a specified token name (looks like right now we are only testing the placeholder case)

2024-12-23 17:36 UTC, fmaclen commented on e2e/export.test.ts
> +		await page.getByRole('tab', { name: 'CSS', exact: true }).click();
I don't think `tab` is a valid "role". This is likely going to be a segmented control element so these will probably be a role of `button`.

2024-12-24 21:41 UTC, GregoMac1 commented on src/lib/palette.svelte.ts
>  	}
@fmaclen this logic was moved to the palette context because we're going to need the already calculated variants in the export panel.

2024-12-26 14:16 UTC, fmaclen commented on src/routes/ExportPanel.svelte
> +	});
Minor suggestion:

```suggestion
	$effect(() => textToExport = formatExport(paletteContext.colors);
```

2024-12-26 14:16 UTC, fmaclen commented on src/routes/ExportPanel.svelte
> +	const paletteContext = getPaletteContext();
Let's rename this to `palette` to match the changes in #43

2024-12-26 14:16 UTC, fmaclen commented on src/routes/ColorCard.svelte
>  <script lang="ts">
Once we merge #43 we can probably remove all of the changes in this file.

2024-12-26 14:21 UTC, fmaclen commented on e2e/export.test.ts
> +		await page.getByRole('tab', { name: 'CSS', exact: true }).click();
Never mind, I looked it up and it turns out `tab` is a valid role. Let's keep it.

2024-12-26 14:29 UTC, GregoMac1 commented on src/routes/ExportPanel.svelte
> +	});
This throws the following error:
`Type 'string' is not assignable to type 'void | (() => void)'.`

2024-12-26 14:45 UTC, fmaclen commented on src/routes/ExportPanel.svelte
> +	});
Oh yeah, that makes sense cause it's an assignment.

2024-12-26 14:50 UTC, fmaclen commented on src/routes/ExportPanel.svelte
> +	const formats: Format[] = ['CSS', 'SCSS', 'Tailwind', 'JSON'];
We need some logic so that CSS, SCSS and Tailwind are display a "Download full version` when `PUBLIC_IS_DEMO`.

2024-12-26 15:21 UTC, GregoMac1 commented on src/routes/ColorCard.svelte
>  <script lang="ts">
Done! I reverted my `name` changes for the inputs.

2024-12-26 15:48 UTC, fmaclen commented on src/routes/ColorCard.svelte
>  <script lang="ts">
There are still [a couple of styling deletions](https://github.com/fmaclen/chromabox/pull/39/files#diff-4a6d1975e1f3391dd0c4610b321275a161a4437764b052fe02e2be75f71f4e39L176-L183) that need to be restored.

2024-12-28 23:50 UTC, GregoMac1 commented on src/routes/ExportPanel.svelte
> +	const formats: Format[] = ['CSS', 'SCSS', 'Tailwind', 'JSON'];
I've been thinking about this change. I think I don't completely understand it. Should it be a button that redirects to the Gumroad page?

2024-12-28 23:56 UTC, fmaclen commented on src/routes/ExportPanel.svelte
> +	const formats: Format[] = ['CSS', 'SCSS', 'Tailwind', 'JSON'];
I was thinking it'd look more like the `No sessions` empty state in Hollama:

![image](https://github.com/user-attachments/assets/67e63613-678d-4e33-afc5-d9e797111617)

It could read:
```
SCSS export is available the [full version].
```

The `[full version]` links to `https://fmaclen.gumroad.com/l/chromabox`

2024-12-28 23:57 UTC, GregoMac1 commented on src/routes/ExportPanel.svelte
> +	const formats: Format[] = ['CSS', 'SCSS', 'Tailwind', 'JSON'];
Awesome, thanks! I'm on it.

2024-12-29 02:27 UTC, fmaclen requested changes
Almost there, left you some notes below.

2024-12-29 02:27 UTC, fmaclen commented on src/routes/ExportPanel.svelte
> +				<a class="export-panel__demo-link" href="https://fmaclen.gumroad.com/l/chromabox">
Make this `target="_blank"`

2024-12-29 02:27 UTC, fmaclen commented on src/routes/ExportPanel.svelte
> +		{/each}
When there is no color in the Palette:
![image](https://github.com/user-attachments/assets/36c02aec-24d2-4a2d-a65c-873887d7f3a3)

---

Add an empty message:
```
No color variants to be exported
```

Don't forget to add assertions for the empty message, a positive and a negative should do.

2024-12-29 02:27 UTC, fmaclen commented on src/routes/+page.svelte
> +<ExportPanel />
This component is still growing beyond the allocated space:

![image](https://github.com/user-attachments/assets/b8275143-2ac1-43cd-b45e-8170a45eeba2)

2024-12-29 02:27 UTC, fmaclen commented on src/routes/ExportPanel.svelte
> +				<a class="export-panel__demo-link" href="https://fmaclen.gumroad.com/l/chromabox">
Also, make sure that in `PUBLIC_IS_DEMO` the `JSON` output is the default active tab.

2024-12-29 02:27 UTC, fmaclen commented on src/routes/ExportPanel.svelte
> +	const formats: Format[] = ['CSS', 'SCSS', 'Tailwind', 'JSON'];
Add a short test in `demo.test.ts` that asserts that the exports are locked in the demo environment.

2024-12-29 21:25 UTC, fmaclen commented on src/routes/ExportPanel.svelte
> +				<A href={STORE_URL}> full version </A>.
We are including this link in multiple places so I set it as constant.

2024-12-29 23:28 UTC, fmaclen commented on e2e/docs.test.ts-snapshots/palette-darwin.png
@GregoMac1 I updated the styles to match the existing components.

2024-12-29 23:30 UTC, fmaclen commented on src/routes/+page.svelte
> +<ExportPanel />
I pushed a fix for this. `<ExportPanel>` is now a [_sticky_](https://github.com/fmaclen/chromabox/pull/39/files#diff-9e31702e3e268d6508a49e4a6632d7f7a2c774ee28429e74da01a180cd74496dR104) sibling of `<ColorCard>`.

2024-12-30 15:13 UTC, fmaclen approved these changes
LGTM! 🚀

2024-12-30 16:56 UTC, merged